//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by InterCom.rc
//
#define ID_EXP                          2
#define ID_CLEAR                        3
#define ID_SEND                         3
#define ID_DEL                          3
#define ID_IMAGES                       4
#define ID_SAVE                         5
#define ID_LAST                         6
#define ID_NEXT                         7
#define ID_PREV                         8
#define ID_FIRST                        9
#define ID_DELETE                       10
#define ID_ADD                          11
#define ID_OPEN                         12
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      102
#define IDR_MAINFRAME                   128
#define IDR_INTERCTYPE                  129
#define IDR_COMMERCE                    129
#define IDD_FFS                         130
#define IDD_FIBH                        131
#define IDI_NEXT                        131
#define IDI_LAST                        132
#define IDD_RFS                         132
#define IDI_PREV                        133
#define IDD_DICTIONARY                  133
#define IDI_FIRST                       134
#define IDD_DICED                       134
#define IDD_EXPINT                      135
#define IDI_ADD                         136
#define IDD_IMPROP                      136
#define IDI_DEL                         137
#define IDI_EDIT                        138
#define IDD_CERROR                      139
#define IDB_DU                          140
#define IDD_COMFS                       140
#define IDI_PLAN                        140
#define IDB_PLOGO                       141
#define IDI_DEFINE                      141
#define IDI_PUNKT                       142
#define IDR_INFORMTYPE                  143
#define IDI_PHOTO                       144
#define IDD_IMS                         145
#define IDI_CLIP                        146
#define IDI_ICON                        150
#define IDD_PRESS_EXPORT                151
#define ID_COL_1                        1000
#define IDC_LBXST                       1000
#define ID_ID                           1000
#define ID_DISTRICT                     1001
#define IDC_PHONE_YN                    1001
#define ID_ADDRESS                      1002
#define IDC_LIST                        1002
#define IDC_ROOMS                       1003
#define ID_AGENT                        1003
#define ID_CHANGE                       1003
#define IDC_SGENERAL                    1004
#define ID_ROOMS                        1004
#define IDC_DICT                        1004
#define IDC_SKITCHEN                    1005
#define ID_METRO                        1005
#define IDC_VALUE                       1005
#define IDC_SPLOT                       1005
#define IDC_R1                          1006
#define ID_FLOORS                       1006
#define IDC_FFS                         1006
#define IDC_CEILINGHEIGHT               1006
#define IDC_R2                          1007
#define ID_SGENERAL                     1007
#define IDC_RFS                         1007
#define IDC_R3                          1008
#define ID_SKITCHEN                     1008
#define IDC_FIBH                        1008
#define IDC_R4                          1009
#define ID_SROOMS                       1009
#define IDC_FFL                         1009
#define IDC_R5                          1010
#define ID_HTYPE                        1010
#define IDC_RFL                         1010
#define IDC_R6                          1011
#define ID_WC                           1011
#define IDC_LOG                         1011
#define IDC_R7                          1012
#define ID_PRICE                        1012
#define IDC_PROGRESS                    1012
#define IDC_R8                          1013
#define ID_B_END                        1013
#define IDC_ENTRANCE                    1013
#define IDC_R9                          1014
#define ID_DESCRIPTION                  1014
#define IDC_CONDITION                   1014
#define IDC_R10                         1015
#define ID_A_PHONE                      1015
#define IDC_DOORWAY                     1015
#define IDC_R11                         1016
#define ID_RRN                          1016
#define IDC_APPOINTMENT                 1016
#define IDC_R12                         1017
#define ID_PHONE                        1017
#define IDC_R13                         1018
#define ID_OBJ_TYPE                     1018
#define IDC_ELECTRICITY                 1018
#define IDC_R14                         1019
#define ID_ENTRANCE                     1019
#define IDC_WATERSUPPLY                 1019
#define IDC_R15                         1020
#define ID_CONDITION                    1020
#define IDC_HEATING                     1020
#define IDC_R16                         1021
#define ID_COMMUNICATIONS               1021
#define IDC_SEWERAGE                    1021
#define IDC_R17                         1022
#define ID_SPLOT                        1022
#define IDC_APHONE                      1022
#define IDC_R18                         1023
#define ID_DOORWAY                      1023
#define IDC_IMNUM                       1023
#define IDC_R19                         1024
#define ID_CEILINGHEIGHT                1024
#define IDC_PARKING                     1024
#define IDC_R20                         1025
#define ID_ELECTRICITY                  1025
#define IDC_GUARD_S                     1025
#define IDC_AGENT                       1026
#define ID_WATERSUPPLY                  1026
#define IDC_FLOOR                       1027
#define ID_HEATING                      1027
#define IDC_FLOORS                      1028
#define ID_SEWERAGE                     1028
#define IDC_SCROLLBAR1                  1028
#define IDC_WC                          1029
#define ID_APPOINTMENT                  1029
#define IDC_FIRE_S                      1029
#define IDC_DEF                         1029
#define IDC_HOUSETYPE                   1030
#define ID_PARKING                      1030
#define IDC_COSTFROM                    1031
#define ID_GUARD_S                      1031
#define IDC_FORWHAT                     1032
#define ID_FIRE_S                       1032
#define IDC_COM                         1032
#define IDC_DISTRICT                    1033
#define IDC_METRO                       1034
#define IDC_PLAN                        1034
#define IDC_DISTANCE                    1035
#define IDC_PHOTO                       1035
#define IDC_INWHAT                      1036
#define IDC_ADDRESS                     1037
#define IDC_BUILDINGEND                 1038
#define IDC_WROOMS                      1038
#define IDC_PHONE                       1039
#define IDC_LIST1                       1039
#define IDC_DESCRIPTION                 1040
#define IDC_RENTERS                     1041
#define IDC_NEIGHBOURS                  1042
#define IDC_OBJ_TYPE                    1043
#define ID_GO                           32771
#define ID_LISTINGS_FLATS_FS            32771
#define ID_SERVICE_EDITTABLE            32772
#define ID_SERVICE_AGENTS               32772
#define ID_RECORD_EDIT_CUR              32773
#define ID_RECORD_ADD                   32774
#define ID_RECORD_DELETE_CUR            32775
#define ID_SERVICE_APHONES              32776
#define ID_SERVICE_SPR_HTYPES           32777
#define ID_SERVICE_OPTIONS              32778
#define ID_LISTINGS_ROOMS_FS            32779
#define ID_FILE_EXPORT_PRESS            32780
#define ID_FILE_EXPORT_INTERNET         32781
#define ID_FILE_EXPORT_XML              32782
#define ID_RECORD_DELETE_ALL            32783
#define ID_LISTINGS_FLATSINBH           32784
#define ID_LISTINGS_FALTS_A             32785
#define ID_LISTINGS_FLATS_A             32785
#define ID_LISTINGS_ROOMS_A             32786
#define ID_SERVICE_SPR_WC               32789
#define ID_FILE_MODE_ADMIN              32790
#define ID_FILE_MODE_OPERATOR           32791
#define ID_LISTINGS_COM_FS              32792
#define ID_LISTINGS_COM_FR              32793
#define ID_SERVICE_SPR_OBJTYPES         32794
#define ID_SERVICE_SPR_CONDITION        32795
#define ID_SERVICE_SPR_APPOINTMENT      32796
#define ID_SERVICE_SPR_DOORWAY          32797
#define ID_SERVICE_SPR_ENTRANCE         32798
#define ID_INDICATOR_SN                 59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
